architecture: replication
auth:
  enabled: true
  password: "YourStrong@Passw0rd"

master:
  startupProbe:
    enabled: true
    failureThreshold: 20
    periodSeconds: 10
  persistence:
    enabled: true
    storageClass: "nfs-client"
    accessModes:
      - ReadWriteOnce
    size: 2Gi

replica:
  replicaCount: 3
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  persistence:
    enabled: true
    storageClass: "nfs-client"
    accessModes:
      - ReadWriteOnce
    size: 2Gi
