apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      # Optional: you can specify a nodePort between 30000-32767
      nodePort: 30379
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: my-redis
    app.kubernetes.io/component: master
