<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c33c1427-6955-4bc9-8680-102593e93ce9</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>  
    <PackageReference Include="Ardalis.ApiEndpoints" />
    <PackageReference Include="Ardalis.ApiEndpoints.Swashbuckle" />
    <PackageReference Include="AspNetCore.HealthChecks.AzureApplicationInsights" />
    <PackageReference Include="AspNetCore.HealthChecks.AzureServiceBus" />
    <PackageReference Include="ChristopherBriddock.AspNetCore.Extensions" />
    <PackageReference Include="ChristopherBriddock.AspNetCore.HealthChecks" />
    <PackageReference Include="DotNetEnv" />
    <PackageReference Include="Fido2" />
    <PackageReference Include="Fido2.AspNet" />
    <PackageReference Include="FluentValidation.AspNetCore" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" />
    <PackageReference Include="MassTransit.Azure.ServiceBus.Core" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="Microsoft.ApplicationInsights" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" />
    <PackageReference Include="Microsoft.ApplicationInsights.Kubernetes" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="Ulid" />
    <PackageReference Include="ZiggyCreatures.FusionCache" />
    <PackageReference Include="ZiggyCreatures.FusionCache.Backplane.StackExchangeRedis" />
    <PackageReference Include="ZiggyCreatures.FusionCache.OpenTelemetry" />
    <PackageReference Include="ZiggyCreatures.FusionCache.Serialization.SystemTextJson" />
  </ItemGroup>

  <ItemGroup>
  <Content Update="appsettings.Development.json">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
  </Content>
  <Content Update="appsettings.json">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
  </Content>
</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Authentica.Common\Authentica.Common.csproj" />
  </ItemGroup>

</Project>
