apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentica-worker-email
  namespace: authentica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentica-worker-email
  template:
    metadata:
      labels:
        app: authentica-worker-email
    spec:
      containers:
      - name: worker-container
        image: 172.16.16.103:30679/authentica-workerservice-email:latest
        env:
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://10.97.200.223:4317"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "2"
