services:
  
  authentica.service.identity:
    image: ${DOCKER_REGISTRY-}authenticaserviceidentity
    build:
      context: .
      dockerfile: Dockerfile.service.identity
    environment: 
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      ASPNETCORE_HTTPS_PORTS: 7171
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - "7171:7171"

  authentica.workerservice.email:
    image: ${DOCKER_REGISTRY-}authenticaworkerserviceemail
    build:
      context: .
      dockerfile: Dockerfile.workerservice.email
    environment: 
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      ASPNETCORE_ENVIRONMENT: "Production"

  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15671:15671"
      - "15691:15691"
      - "15692:15692"
      - "25672:25672"
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    hostname: sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    restart: always
  
  redis:
    image: redis:latest
    hostname: redis
    container_name: test-redis
    ports:
      - "6379:6379"
    restart: always
    
  aspire-dashboard:
    hostname: "aspire-dashboard"
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.0.0
    ports:
      - "18888:18888"
      - "4317:18889"
    container_name: aspire-dashboard
    restart: unless-stopped

volumes:
  sqlserverdata:
    driver: local

